name: simple_navigation
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  riverpod_navigator: ^0.28.0
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
